version: '3.7'

x-base-service: &base-service
  build: .
  restart: on-failure:5
  volumes:
    - ./:/app
  depends_on:
    - redis
  tty: true
  stdin_open: true

services:
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  worker:
    <<: *base-service
    entrypoint: dramatiq tasks

  scheduler:
    <<: *base-service
    entrypoint: python schedule.py
